GET http://localhost:8000/entries/pageEntries/1

###
GET http://localhost:8000/entries/openedEntry/1

###
GET http://localhost:8000/entries/entryDetails/1

###
POST http://localhost:8000/entries
Content-Type: application/json

{
    "medicationId": 1,
    "date": "2026-12-12",
    "generalEffectiveness": 5,
    "genrealSideEffects": 8,
    "userNote": "Hallo TEST"
}

###
PUT http://localhost:8000/entries/1
Content-Type: application/json

{
    "generalEffectiveness": 10,
    "generalSideEffects": 0,
    "userNote": "Put TEST",
    "Ratings": [
        {
            "starRatingId": 1,
            "Rating": 0
        },
        {
            "starRatingId": 2,
            "rating": 0
        }
    ]
}

###
DELETE http://localhost:8000/entries/1